### PR TITLE
ENH add new parameters to civis_ml training and prediction

### PR DESCRIPTION
**Pull request by elsander**
This PR adds `validation_data` and `n_jobs` as arguments for training, and `cpu`, `memory`, and `disk_space` as arguments for prediction.

### CODE REVIEW

**Comment by elsander** [comment]
Oops-- I had the arguments in slightly different orders in a couple of methods. That should be fixed now.

Something I noticed, @patr1ckm: `polling_interval` is taken as an input argument to these functions, but isn't passed through to `create_and_run_model`. Is there a reason for that? If not, I can go ahead and add it in this PR, while I'm at it.

**Comment by patr1ckm** [comment]
It's also not passed to `run_model` and then finally to `await`. If you want to fix that here, that would be awesome.

**Comment by elsander** [comment]
Ok, that should do it. I also decided to rename `cpu`, `memory`, and `disk_space` to match the training arguments, for clarity to users.

**Comment by elsander** [comment]
Sure, just pushed the changes!

**Pull request merged**
